{% set version = '2.0-5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ada
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ada_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ada/ada_{{ version }}.tar.gz
  sha256: d900172059eebeef30c27944fc29737a231fc4f92e3c2661868383fbd9016ac0

build:
  merge_build_host: True  # [win]
  number: 1004
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rpart
  run:
    - r-base
    - r-rpart

test:
  commands:
    - $R -e "library('ada')"           # [not win]
    - "\"%R%\" -e \"library('ada')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ada
  license: GPL-2.0-or-later
  summary: Performs discrete, real, and gentle boost under both exponential and  logistic loss
    on a given data set.  The package ada provides a straightforward,  well-documented,
    and broad boosting routine for classification, ideally suited  for small to moderate-sized
    data sets.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
