travis:
  secure:
    BINSTAR_TOKEN: Iym2R8hhJmK3TZAumOBAllkRAN+NA5iLUr82sdmNPxBMD2EnK/ddikWlukzZhwoBeDeHYGvc1fZRLQ5izt6tTQEGYGQSyPU9tjCklgDOGq83QThUDEaqZ6hZUY+IYdZ0pvmYmgry6RhkVCSB8J9KVRM/pq1sxsWa4/FvPK/eRzdREoo/DU9/5FVxtGDNdncLOS81Lx2zSlVN/4P9IT7RZE9IxmxuH8YhUe29LKnaphDaK3HznGz3SL2E5x+CV23xwMQ9+KbitzysfpiCcnRxQZAU4WvgH3/NzyPcaxTgHU00zuwYp2lslIQi3HkBxMHqzMkZZcHdMidRsDV3Owi6FbxLfLgGit29A3Y5b75kvDrOqzo/UaVmaveNi1j+LGtJLSMRDbZN+VT1/RWpUlmPafT3/c93B+czwSn04b92a/0My/gaAjBBhLuqh/Q+uoC+4QgMl5Fm/x1Fgj45ubIIGWSojiemCp2OhZzuQDEbpkOTO15TAw46FzKRkZpipWQ/bgW7HmjqUKhTIbhJO+n8Y0d0NCd5plSgLwalNypXrGPaMteWEY4Jy6FKxBTllJwAsu57FL9kKZNsQf8daE/nx4s8di9JQdwT/1ObrOH3sQ6sJ4RXMpdPiGg8Kowzj/r/Mj2ri9HVu9cmrLgOxwMczyC1kL/Xvrmo/CYs6GSTk68=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
