appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: pQpx5AnL1NFjZcIRFrWPpMorTPSxTIhlzDsm/dHyFNT/SbC+85mcuGU2jp+fTJM5J3J1BN4+eCaIWIkGsR673zlMaR2bKr36+Ulkw33MPE/JWAgoIVLxJVpqFLyqE/7tHiOmmolzU0HwPERv6jwlspkWTR5XpV7m4h516Za70KTwHLt5LTpgKwsq8WPQUX+83B479AMArSP5/sXi+6LkhpbIhw+B733xUw8YmiuE2kf2UNmFMbRDquKqMkjLSXa/f9NQpol5dFU39+4IqkXwCeR4gYMynbr9QeRsJb+UhbWz0hkLhJoUOC4usE2U7kWUkPozA0Vh21uacNjOmAqV4V/uyBjWp5Tod1aTxZQNeV6bLDI8XrdtTgGtP2xeL0cH8+NdCpPdMKqG2dVmVLXFQZiYx1iQGWoK/A6kDVaR9WXgWTc4mPhD3xvjgmt0Mz2fURaPihJm/ZgH+LBj9121oDnHAaIRlqIEtslxCzcioDM6m6DblwjD72E2V6Fi4gmFpuXdNQwJK4BUsUl9SbL6MmMbkxLFrAhg+vWPeS+NVy2meuvwgxmkC8Y94Y0FyomgLFmRB29ydFj5Dg3htNSrloAS3iTz3NHIw9eeVyohckmZ36N/sZa7GpGp5a7E23MsVc54UqcHZk+FuUqcXohXiJSXi4Ho2joN5EtZt0/IuqU=}
